pg9182/northstar-dedicated

- src/entrypoint/nsinstance.go
These changes allow the entrypoint to terminate if the Northstar launcher crashes, allowing proper auto-restart functionality with docker-compose. Since `sendTerminate(true)` is deferred to the end of `n.Run()`, extra calls within `Run()` are not required. Also, initialising Xrdb now removes old lock files, which in my case were preventing the docker container from restarting successfully.
> Fix entrypoint hanging when launcher crashes

- src/entrypoint/nsconfig.go
Apparently some convars can't be set in the autoexec file, meaning attempting to set them with `NS_EXTRA_ARGUMENTS` kinda breaks servers(?).
This PR fixes this behavior by always passing these extra convars to Northstar on the command-line, unless they're overriding a convar set by a builtin default or hardcoded environment variable.
For example, this means a command-line like:
```
-e NS_SERVER_NAME Test -e NS_EXTRA_ARGUMENTS="+ns_should_return_to_lobby 0 +map mp_glitch"
```
will set `ns_server_name` and `ns_should_return_to_lobby` in the autoexec file, and pass `+map mp_glitch` as command-line arguments.
> Pass convars as arguments when possible

- src/entrypoint/nsconfig.go
**Issue:** Setting an extra argument to a value starting with a dash does not work, e.g.:
```sh
-e NS_EXTRA_ARGUMENTS="+slide_step_velocity_reduction -1000"
```
This ends up running the dedicated server like:
```sh
NorthstarLauncher.exe "+slide_step_velocity_reduction" "-1000"
```
The dedicated server is probably interpreting the `-1000` as a command-line flag, so it's ignored when parsing the actual args.
**Solution:** This PR forces convars to be set in the generated autoexec file if the value starts with a dash, ensuring the value is parsed as a number and not a flag.
One possible alternative is wrapping values in an extra pair of quotes, i.e.:
```sh
NorthstarLauncher.exe "+slide_step_velocity_reduction" "\"-1000\""
```
However the launcher doesn't seem to be capable of parsing values …
> Set convars in autoexec if the value starts with a dash

- src/entrypoint/nsinstance.go
Took a look at my own logs of the day and it doesn't seems like there's many hits above 300 chars per lines (they do exist though).
I've set it to a much higher value since it apparently still plays nice with Wine and should cover just about everything..!
updates #11
> Bump pty column size to 1200 to prevent unnecessary line breaks

- src/northstar/APKBUILD
`ghcr.io/cpdt/northstar-dedicated-dev:dev.20220515.git304835f` is verified to start and load.
> Update Northstar to v1.7.1

- src/northstar/APKBUILD
Noticed that we didn't even updated to `v1.13.1` of Northstar yet.
> Update Northstar to v1.13.1

- src/northstar/APKBUILD
Obligatory disclaimer that I did not test it. But there were only [2 changes in this update ](https://github.com/R2Northstar/Northstar/releases/tag/v1.14.1) and none of them are breaking in terms of Docker image so it should be fine™
> Update Northstar to v1.14.1

- src/northstar/APKBUILD
https://github.com/R2Northstar/Northstar/releases/tag/v1.14.2
This contains an important bugfix that caused all Attrition servers since `v1.13.0` to crash.
> Update Northstar to v1.14.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.16.3`.
> Update Northstar to v1.16.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.17.0`.
> Update Northstar to v1.17.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.17.1`.
> Update Northstar to v1.17.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.17.2`.
> Update Northstar to v1.17.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.17.3`.
> Update Northstar to v1.17.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.18.0`.
> Update Northstar to v1.18.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.18.1`.
> Update Northstar to v1.18.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.18.2`.
> Update Northstar to v1.18.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.18.3`.
> Update Northstar to v1.18.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.0`.
> Update Northstar to v1.19.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.1`.
> Update Northstar to v1.19.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.2`.
> Update Northstar to v1.19.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.3`.
> Update Northstar to v1.19.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.4`.
> Update Northstar to v1.19.4

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.5`.
> Update Northstar to v1.19.5

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.6`.
> Update Northstar to v1.19.6

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.7`.
> Update Northstar to v1.19.7

- src/northstar/APKBUILD
This reverts commit 63e0d25f8430c93daceac167bf6b4ff78160c01b  (#75)
The reason for revert is due to issues with Wine and curl in `v1.19.7`
> Revert "Update Northstar to v1.19.7"

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.8` which reverts the curl update
> Update Northstar to v1.19.8

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.10`.
> Update Northstar to v1.19.10

- src/northstar/APKBUILD
Updates Northstar to release `v1.19.11`.
> Update Northstar to v1.19.11

- src/northstar/APKBUILD
Updates Northstar to release `v1.20.0`.
> Update Northstar to v1.20.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.20.1`.
> Update Northstar to v1.20.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.20.2`.
> Update Northstar to v1.20.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.20.3`.
> Update Northstar to v1.20.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.21.0`.
> Update Northstar to v1.21.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.21.1`.
> Update Northstar to v1.21.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.21.2`.
> Update Northstar to v1.21.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.21.3`.
> Update Northstar to v1.21.3

- src/northstar/APKBUILD
Updates Northstar to release `v1.21.4`.
> Update Northstar to v1.21.4

- src/northstar/APKBUILD
Updates Northstar to release `v1.22.0`.
> Update Northstar to v1.22.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.22.1`.
> Update Northstar to v1.22.1

- src/northstar/APKBUILD
Updates Northstar to release `v1.22.2`.
> Update Northstar to v1.22.2

- src/northstar/APKBUILD
Updates Northstar to release `v1.23.0`.
> Update Northstar to v1.23.0

- src/northstar/APKBUILD
Updates Northstar to release `v1.23.1`.
> Update Northstar to v1.23.1

- src/northstar/APKBUILD
> Update Northstar to v1.29.1
