- src/northstar/APKBUILD
Just edited the APKBUILD file with the right version and checksum. No testing done if that's something you do before updating release.
Though this update only has changes in NorthstarMods so any potential new bugs should not be specific to Docker.
> Update Northstar to v1.9.3

- src/northstar/APKBUILD
@GeckoEidechse pushed the wrong file, supersedes #38 
Tested to launch.
> Update Northstar to v1.9.4

- src/northstar/APKBUILD
Will push 1.10.5 next, just doing this first so we don't have a missed release.
> Update Northstar to v1.10.4

- src/entrypoint/nsoverlay.go
Should resolve (not tested though)
> Remove placeholder_playerdata check from nsoverlay

- src/northstar/APKBUILD
> Update Northstar to v1.24.0

- src/northstar/APKBUILD
> Update Northstar to v1.24.1

- src/northstar/APKBUILD
> Update Northstar to v1.24.2

- src/northstar/APKBUILD
> Update Northstar to v1.24.3

- src/northstar/APKBUILD
> Update Northstar to v1.24.4

- src/northstar/APKBUILD
> Update Northstar to v1.24.5

- src/northstar/APKBUILD
> Update Northstar to v1.24.6

- src/northstar/APKBUILD
> Update Northstar to v1.25.0

- src/northstar/APKBUILD
> Update Northstar to v1.25.1

- src/northstar/APKBUILD
> Update Northstar to v1.25.2

- src/northstar/APKBUILD
> Update Northstar to v1.25.3

- src/northstar/APKBUILD
> Update Northstar to v1.25.4

- src/northstar/APKBUILD
> Update Northstar to v1.26.0

- src/northstar/APKBUILD
> Update Northstar to v1.26.1

- src/northstar/APKBUILD
> Update Northstar to v1.26.2

- src/northstar/APKBUILD
> Update Northstar to v1.26.3

- src/northstar/APKBUILD
> Update Northstar to v1.26.4

- src/northstar/APKBUILD
> Update Northstar to v1.27.0

- src/northstar/APKBUILD
> Update Northstar to v1.27.1

- src/northstar/APKBUILD
> Update Northstar to v1.27.2

- src/northstar/APKBUILD
> Update Northstar to v1.27.3

- src/northstar/APKBUILD
> Update Northstar to v1.27.4

- src/northstar/APKBUILD
> Update Northstar to v1.27.5

- src/northstar/APKBUILD
> Update Northstar to v1.27.6

- src/northstar/APKBUILD
> Update Northstar to v1.27.7

- src/northstar/APKBUILD
> Update Northstar to v1.28.0

- src/northstar/APKBUILD
> Update Northstar to v1.28.1

- src/northstar/APKBUILD
> Update Northstar to v1.28.2

- src/northstar/APKBUILD
> Update Northstar to v1.28.3

- src/northstar/APKBUILD
> Update Northstar to v1.28.4

- src/northstar/APKBUILD
> Update Northstar to v1.28.5

- src/northstar/APKBUILD
> Update Northstar to v1.28.6

- src/northstar/APKBUILD
> Update Northstar to v1.29.0

- src/northstar/APKBUILD
> Update Northstar to v1.30.0

- src/northstar/APKBUILD
> Update Northstar to v1.30.1

- src/northstar/APKBUILD
Did not test, but this seems to be the status quo.
> Update Northstar to v1.31.2
